### PR TITLE
Add specs section to ruby style guide

### PR DESCRIPTION
**Pull request by shmartin**
This PR adds a specs section to ruby style guide.

I'm looking for feedback on the current content of this section as well as suggestions for future improvements. However, any additional content will be added via a new PR so that we can have something for people to reference for now.

Also, this section is meant to be an how-to guide but is more of a reference section at the moment. The hope is to iterate and flesh it out more over time.

To view the guide locally, I've been using the [Markdown Preview Plus](https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl?hl=en-US) chrome extension.

### CODE REVIEW

**Comment by willischu** [comment]
going to https://github.com/sema4genomics/ruby-style-guide/blob/87c16c131bd07e32719913bf51a98a10005e4198/README.md/#specs works as well to view the markdown, if you don't want to install the chrome extension

**Comment by shmartin** [comment]
I replaced my previous commit. Click [here](https://github.com/sema4genomics/ruby-style-guide/blob/dfc4a6f2379e70635ec6fc50cc7609e8e77638b0/README.md/#specs) for an updated version of the style guide.

**Comment by laisti** [comment]
@shmartin It's perfect for me! It is clear and easy to follow.

**Comment by shmartin** [comment]
Got some additional feedback from @jkolber. It looks like this would be a better fit in the docs section of our repo since it's more of a how-to guide than a style guide. So I'm closing this PR.

**Pull request closed without merging**
